### ISSUE TITLE
Adding new dotfiles

### ISSUE THREAD

**Issue by fnando** [mdespuits/dotify#1]
Hey!

I have one suggestion: from what I tried, adding a new file means running the `dotify setup` again, which will ask if I want to add every single dotfile, even those I already added.

What about a `dotify add` command, which can be used by the `setup` itself.

Thanks for this handy project! ;)

**Comment by mdespuits** [comment]
@fnando That is a fantastic idea and I already had plans to include it in a future version. I'm hoping to work on this project quite a bit over the next few weeks, so a few more small and helpful little things should get added over that time frame.

**Comment by mdespuits** [comment]
Oh, and you are welcome!
