### ISSUE TITLE
Configurable environment values

### ISSUE THREAD

**Issue by danielbayerlein** [mdespuits/dotify#14]
Hi, any idea how make values configurable in dotfiles?

For example the .gitconfig. In the work I've a other email address than at home.

```
[user]
  name = ...
  email = ...
```

**Comment by mdespuits** [comment]
I think I understand your meaning, but could you elaborate further on the use case?

**Comment by danielbayerlein** [comment]
No problem. I host my dotfiles on GitHub and I use this at home and at work. But i think most people have different settings for work and home, for example the mail address in the .gitconfig. @ryanb managed this issue in his [dotfiles](https://github.com/ryanb/dotfiles) with erb templates and keyboard entry.

My thought: I can manage the environment and the values in the `.dotrc` and replace the values with `dotify setup`. The dotfile has a placeholder for the value.

It's just a thought. :wink:

**Comment by mdespuits** [comment]
@danielbayerlein Yes, I started this whole project in trying to make @ryanb's solution more robust. As I have the same personal and work credentials, it wasn't an issue for me, but I did wonder if this would come up again. I have almost wondered if some other solution would be better than manually editing them myself. I like the idea and will look for a strong solution within the next few weeks.

**Comment by danielbayerlein** [comment]
@mattdbridges :+1:

**Comment by mdespuits** [comment]
@danielbayerlein Quick idea to bounce off you. What do you think of moving the configuration into a ruby file instead of a yaml file? It would make configuration a little easier to manage and you could (in theory) take advantage of Ruby methods and abilities instead of messing with yaml. I would love to do this for myself, but I wouldn't want to make any presumptions...

**Comment by danielbayerlein** [comment]
@mattdbridges Oh yes, i like your idea!

**Comment by mdespuits** [comment]
See the [CHANGELOG](https://github.com/mattdbridges/dotify/blob/master/CHANGELOG.md) for upcoming work on this issue.

**Comment by kylewest** [comment]
Check out how we handled it in the YADR project. https://github.com/skwp/dotfiles#user-info

The .gitconfig doesn't include any user information. That info is set in a `~/.secrets` file that is included by zshrc. You end up with a file that isn't part of the repo, but you probably don't want your GitHub credentials in the repo anyway.

Kyle

**Comment by mdespuits** [comment]
@danielbayerlein Much has changed in Dotify behind the scenes in the last several weeks. I have been working on a complete rewrite of the codebase for potential extensibility as well as cleaner code. This feature is not currently at the forefront of priorities, but I'm hoping that this could be added in the future.

At the moment, the DSL that I am implementing currently detects general OSese for platform-specific symlinks. This same pattern could potentially be used on a per-computer (same platform) basis as you suggest. I will follow up with ideas and more details as I get farther along.

Cheers!

**Comment by funglaub** [comment]
Really cool idea

+1

**Comment by svenwin** [comment]
This idea is really awesome!

+1

**Comment by danielbayerlein** [comment]
I close the issue because this repo is no longer maintained.
