### ISSUE TITLE
Configuration link broken

### ISSUE THREAD

**Issue by dagda1** [mdespuits/dotify#18]
Hi,

The link to the dotify configuration is broken in the readme (https://github.com/mattdbridges/dotify/tree/cli-rewrite#configuration).

How do I specify which github repo I should be backing up to?

Thanks 

Paul

**Comment by mdespuits** [comment]
Thanks!

**Comment by mdespuits** [comment]
I'm not quite sure I understand the backup question? Could you elaborate?

**Comment by dagda1** [comment]
I mean, how do I get my setup into github?

Do I have to manually add the files to github?

**Comment by mdespuits** [comment]
No, all you have to do is make your `~/.dotify` directory a git repository that has a remote on GH, so all you have to do is create the repo on GH and have `~/.dotify` have a remote pointing to it:

```
$ cd ~/.dotify
$ git init
$ git add .
$ git commit -m "initial commit"
$ git remote add origin git@github.com:USERNAME/REPOSITORY.git
$ git push # or `dotify save`
```
