### ISSUE TITLE
Updating dotfiles

### ISSUE THREAD

**Issue by axsuul** [mdespuits/dotify#20]
First off, great gem and tool! Is there a way to update the dotfiles (pull from repo)? Or do I have to unlink each individual file and then install them again?

**Comment by axsuul** [comment]
It looks like this gets me what I want, although it would be nice if this could be aliased!

``` bash
$ cd .dotify && git pull
$ dotify unlink --force
$ dotify link --force
```

`unlink` in case some dotfiles have been removed from the repo.

**Comment by mdespuits** [comment]
Technically, no. I wish there was a good way to it at the moment. Right now, we're kinda stuck until I can get my re-write finished (which will be soon, I hope). Until then, I would suggest making it an actual terminal alias.

```
alias dotify_update="cd .dotify && git pull; dotify unlink --force; dotify link --force"
```
