### ISSUE TITLE
Setup on a second machine from git

### ISSUE THREAD

**Issue by ashchan** [mdespuits/dotify#6]
Say I've installed and setup on one machine, and added .dotify to a git repository.

Now since I want to use the same dotfiles cross all my machines, I installed dotify on another machine. Then how can I fetch the git repository and setup dotify based on it?

It seems I need to copy all files out of the .dotify folder to my home folder, then do a link or setup manually?

How about adding a command to delete existing files under home folder, copy these files from .dotify, then link them automatically?

**Comment by mdespuits** [comment]
@ashchan Yes, that has been in the back of my mind for a while. I have been focusing on re-writing most of the classes for better OO design, maintainability, and testing. However what you mentioned is an importnat aspect of the project and will be included in a near-future release (likely 0.7).

I'll be brainstorming over the next few days. I welcome your thoughts on a useful task name if you have any suggestions.

**Comment by mdespuits** [comment]
In fact, I have had the idea of being able to set them up by running something like `dotify github ashchan/dotfiles` and it will clone and link everything automatically. Sound like a good solution to you?

**Comment by ashchan** [comment]
Matt,

Yes, this would be super awesome! Looking forward to this feature.

Thank you for the great work on it!

James

在 Jul 16, 2012，21:55，Matt Bridgesreply@reply.github.com 写道：

**Comment by mdespuits** [comment]
I think that [this task](https://github.com/mattdbridges/dotify/blob/72e51ce7fdceed6a3fca8c63f80d32a13dccc665/lib/dotify/cli.rb#L67) will do the trick when I release the next version.

**Comment by ashchan** [comment]
Awesome! Thanks a lot!

**Comment by mdespuits** [comment]
Dotify v0.6.6 is out (a381e5b5)

**Comment by ashchan** [comment]
Just tried it on a new machine and it worked like a charming!
